language: node_js
node_js:
- 4
- 6
- 7
deploy:
  provider: npm
  on:
    tags: true
  email: ben@byk.im
  api_key:
    secure: QDWymqZbfwIqsyjsN4/SvQyyEo230w8a5Ppr7hCWhFoW+Lo/8Y8W5nPc+uZhP1Wx7EJJTkGVSztXVef1QNfZnNFcO3+mYL9UQBuvoHseAZ0Rar8AwtN8/SbhvuflosnIGVyUBE1VTAT8cXPEusZ6AUrFsf+6T/Qj3sGvObVuEvI=
